### PR TITLE
Quick Look Thumbnails + Document Icon support 

### LINKED ISSUE #26: .gpx file icon is either blank or is generic text file icon
Reported via email. 

OS: macOS High Sierra.

### PR DESCRIPTION
**Pull request by vincentneo**
Example:
Screenshot 2023-01-14 at 12 33 28 AM

Fix #26, ~~but only if user's OS is macOS 10.15 or above, which I see as an ok compromise.~~ 
Quick Look Thumbnails for macOS 10.15 and above, but macOS 10.14 users (or users that do not wish to use Quick Look thumbnails) gets a static icon too:

pre macOS 11:
Screenshot 2023-01-14 at 5 19 14 PM

macOS 11 and above:
Screenshot 2023-01-14 at 5 20 19 PM

### CODE REVIEW

**Comment by pvdb** [comment]
I recognise that GPX file!  😉

**Comment by pvdb** [comment]
Awesome!!!

image

**Comment by pvdb** [comment]
So... this is weird: yesterday it was fine in Finder, and today it's back to using generic text icons! :confused:

##### yesterday

yesterday

##### today

today

**Comment by vincentneo** [comment]
Hmm... and the non-rendered icon didn't show too. Do you mind trying this command out in Terminal and providing the response of it? 

`mdls <drag any gpx file into the Terminal window>` (something like this: `mdls /Users/vincent/Downloads/littlemill_trk.gpx`)

You will get a response like this:

Screenshot 2023-01-17 at 11 50 17 PM


In particular, I need the info for the `kMDItemContentType` and `kMDItemContentTypeTree`. Usually it's discrepancies of those values that causes differences between systems, so knowing that difference usually helps!

**Comment by vincentneo** [comment]
@pvdb, just realise I didn't tag you, in case you miss the earlier message. Feel free to let me know if you aren't comfortable with sharing that info, will find other ways to debug if so. Thanks!
> Do you mind trying this command out in Terminal and providing the response of it?

**Comment by pvdb** [comment]
Hey @vincentneo more than happy to share, just been a tad busy 😄 

FWIW - it's back to showing proper icons for GPX files now, instead of the "generic" one for text files, so it's all good 👍 

_(maybe a recent reboot of my MacBook Air sorted it out properly?)_ 🤔 

but if it's still useful, here's the output you asked for:

```
_kMDItemDisplayNameWithExtensions  = "littlemill_rte.gpx"
kMDItemContentCreationDate         = 2023-01-06 08:25:30 +0000
kMDItemContentCreationDate_Ranking = 2023-01-06 00:00:00 +0000
kMDItemContentModificationDate     = 2023-01-06 08:25:30 +0000
kMDItemContentType                 = "public.gpx"
kMDItemContentTypeTree             = (
    "public.gpx",
    "public.xml",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
kMDItemDateAdded                   = 2023-01-06 08:25:30 +0000
kMDItemDisplayName                 = "littlemill_rte.gpx"
kMDItemDocumentIdentifier          = 0
kMDItemFSContentChangeDate         = 2023-01-06 08:25:30 +0000
kMDItemFSCreationDate              = 2023-01-06 08:25:30 +0000
kMDItemFSCreatorCode               = ""
kMDItemFSFinderFlags               = 0
kMDItemFSHasCustomIcon             = (null)
kMDItemFSInvisible                 = 0
kMDItemFSIsExtensionHidden         = 0
kMDItemFSIsStationery              = (null)
kMDItemFSLabel                     = 0
kMDItemFSName                      = "littlemill_rte.gpx"
kMDItemFSNodeCount                 = (null)
kMDItemFSOwnerGroupID              = 20
kMDItemFSOwnerUserID               = 501
kMDItemFSSize                      = 7827
kMDItemFSTypeCode                  = ""
kMDItemInterestingDate_Ranking     = 2023-01-16 00:00:00 +0000
kMDItemKind                        = "GPX File"
kMDItemLastUsedDate                = 2023-01-16 20:16:34 +0000
kMDItemLastUsedDate_Ranking        = 2023-01-16 00:00:00 +0000
kMDItemLogicalSize                 = 7827
kMDItemPhysicalSize                = 8192
kMDItemUseCount                    = 26
kMDItemUsedDates                   = (
    "2023-01-06 00:00:00 +0000",
    "2023-01-16 00:00:00 +0000"
)
```

**Comment by vincentneo** [comment]
> Hey @vincentneo more than happy to share, just been a tad busy 😄

No problem!

The `mdls` output looks alright, so I'd say it's just a macOS thing and probably it was the reboot that did it's thing 😁

**Comment by pvdb** [comment]
Just reporting that for me it's back to showing the "generic" GPX icons, not the "preview" route/track ones ... but still better than the "text" ones from a while ago :sweat_smile:

I'll try to reboot and report back, but just as an FYI

image

**Pull request merged**
